- name: upload apiserver TLS assets
  copy: content={{ item.content }} dest={{ item.dest }} mode=0644
  sudo: true
  with_items:
  - content: "{{ pki_clients.apiserver.cert }}"
    dest: "/etc/kubernetes/apiserver.pem"
  - content: "{{ pki_clients.apiserver.key }}"
    dest: "/etc/kubernetes/apiserver-key.pem"

- name: upload pod manifests
  template: src={{ item }}.j2 dest=/etc/kubernetes/manifests/{{ item }} mode=0644
  sudo: true
  with_items:
  - etcd.yml
  - kube-apiserver.yml
  - kube-scheduler.yml
  - kube-controller-manager.yml
