#!/bin/bash -e

if [ -z "$1" ]; then
	echo "usage: $0 <cluster>"
	exit 2
fi

aws ec2 describe-instances --output text --filters "Name=tag:KubernetesCluster,Values=$1" "Name=tag:group,Values=bastion" --query "Reservations[0].Instances[0].PublicIpAddress"
