apiVersion: v1
kind: Namespace
metadata:
  name: example

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx
  namespace: example
spec:
  backend:
    serviceName: nginx
    servicePort: 80

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: example
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: ClusterIP

---

apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: example
spec:
  replicas: 3
  selector:
    app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
