#!/bin/bash -e

ACTION=$1
CLUSTER=$2
TARBALL=klondike-cluster-$CLUSTER.tar.gz
S3_LOC_TARBALL=s3://$3/$TARBALL
TEMPLATE=stack-template.yaml
S3_LOC_TEMPLATE=s3://$3/$TEMPLATE

function push {
	tar -czf clusters/$TARBALL clusters/$CLUSTER/
	echo "Packed clusters/$CLUSTER/ into clusters/$TARBALL"

	aws s3 cp clusters/$TARBALL $S3_LOC_TARBALL
	echo "Published clusters/$TARBALL to $S3_LOC_TARBALL"

	aws s3 cp clusters/$CLUSTER/$TEMPLATE $S3_LOC_TEMPLATE
	echo "Published clusters/$CLUSTER/$TEMPLATE to $S3_LOC_TEMPLATE"
}

function pull {
	mkdir -p clusters/

	aws s3 cp $S3_LOC_TARBALL clusters/$TARBALL
	echo "Pulled clusters/$TARBALL from $S3_LOC_TARBALL"

	tar -xzf clusters/$TARBALL clusters/$CLUSTER/
	echo "Unpacked clusters/$CLUSTER/ from clusters/$TARBALL"
}

function usage {
	echo "usage: $0 [push|pull] <cluster> <s3-bucket-name>"
	echo "	push: pack the local cluster config into a tarball and publish it to S3"
	echo "	pull: download the cluster config from S3 and unpack it"
	exit 2
}

if [ $# -ne 3 ]; then
	usage
fi

case $1 in
	"push" )
		push ;;
	"pull" )
		pull ;;
	* )
		usage ;;
esac
