#!/bin/bash -e

operating_systems=( "darwin" "linux" )
arch="amd64"
cmd="kube-datadog"
cmd_pkg="github.com/bcwaldon/kube-datadog/cmd"

for os in "${operating_systems[@]}"; do
	bindir=bin/${os}_${arch}
	mkdir -p $bindir
	artifact=$bindir/$cmd
	echo -n "Building $artifact..."
	GOOS=$os GOARCH=$arch go build -o $artifact $cmd_pkg/$cmd
	echo "done"
done
