- hosts: 127.0.0.1
  connection: local
  gather_facts: False
  roles:
  - pki-ca
  vars_files:
  - "{{ playbook_dir }}/vars/main.yml"
  vars:
    workspace: "{{ playbook_dir }}/tmp"
    ca_vars_file: "{{ playbook_dir }}/vars/pki-{{ ca_name }}-ca.yml"
