- hosts: 127.0.0.1
  connection: local
  gather_facts: False
  roles:
  - pki
  vars:
    ca_dir: "{{playbook_dir}}/files/ca-{{ ca_name }}"
    workspace: "{{ playbook_dir }}/tmp"
    ca_vars_file: "{{ playbook_dir }}/vars/pki-{{ ca_name }}-ca.yml"
    client_vars_file: "{{ playbook_dir }}/vars/pki-{{ ca_name }}-clients.yml"
    clients:
    - name: apiserver
      profile: server
      hosts:
      - "{{ control_plane_host }}"
      - 10.200.20.1
    - name: admin
      profile: client
      hosts: []
