- hosts: 127.0.0.1
  connection: local
  gather_facts: False
  roles:
  - pki-clients
  vars_files:
  - "{{ playbook_dir }}/vars/main.yml"
  vars:
    workspace: "{{ playbook_dir }}/tmp"
    ca_vars_file: "{{ playbook_dir }}/vars/pki-{{ ca_name }}-ca.yml"
    client_vars_file: "{{ playbook_dir }}/vars/pki-{{ ca_name }}-clients.yml"
    clients:
    - name: apiserver
      profile: server
      hosts:
      - "{{ external_fqdn }}"
      - "{{ cluster_service_kubernetes_ip }}"
    - name: admin
      profile: client
      hosts: []

- hosts: all
  gather_facts: False
  roles:
  - defunctzombie.coreos-bootstrap

- hosts: tag_group_controller
  gather_facts: False
  roles:
  - kubelet
  - kube-controller
  vars_files:
  - "{{ playbook_dir }}/vars/main.yml"
  - "{{ playbook_dir }}/vars/pki-{{ ca_name }}-ca.yml"
  - "{{ playbook_dir }}/vars/pki-{{ ca_name }}-clients.yml"
    
- hosts: tag_group_worker
  gather_facts: False
  roles:
  - kubelet
  vars_files:
  - "{{ playbook_dir }}/vars/main.yml"
  - "{{ playbook_dir }}/vars/pki-{{ ca_name }}-ca.yml"
  - "{{ playbook_dir }}/vars/pki-{{ ca_name }}-clients.yml"
