- hosts: tag_group_controller
  gather_facts: False
  roles:
  - defunctzombie.coreos-bootstrap
  - kubelet
  - kube-controller
  vars:
    cluster_dir: "clusters/{{ cluster }}"
  vars_files:
  - "{{ cluster_dir }}/main.yml"
  - "{{ cluster_dir }}/pki-{{ ca_name }}-ca.yml"
  - "{{ cluster_dir }}/pki-{{ ca_name }}-clients.yml"
    
- hosts: tag_group_worker
  gather_facts: False
  roles:
  - defunctzombie.coreos-bootstrap
  - kubelet
  vars:
    cluster_dir: "clusters/{{ cluster }}"
    workspace: "{{ cluster_dir }}/tmp"
  vars_files:
  - "{{ cluster_dir }}/main.yml"
  - "{{ cluster_dir }}/pki-{{ ca_name }}-ca.yml"
  - "{{ cluster_dir }}/pki-{{ ca_name }}-clients.yml"
