- hosts: 127.0.0.1
  connection: local
  gather_facts: False
  roles:
  - pki-clients
  vars:
    cluster_dir: "{{ playbook_dir }}/clusters/{{ cluster }}"
    workspace: "{{ cluster_dir }}/tmp"
    ca_vars_file: "{{ cluster_dir }}/pki-{{ ca_name }}-ca.yml"
    client_vars_file: "{{ cluster_dir }}/pki-{{ ca_name }}-clients.yml"
    clients:
    - name: apiserver
      profile: server
      hosts:
      - "{{ external_fqdn }}"
      - "{{ cluster_service_kubernetes_ip }}"
  vars_files:
  - "{{ cluster_dir }}/main.yml"

- hosts: all
  gather_facts: False
  roles:
  - defunctzombie.coreos-bootstrap

- hosts: tag_group_controller
  gather_facts: False
  roles:
  - kubelet
  - kube-controller
  vars:
    cluster_dir: "{{ playbook_dir }}/clusters/{{ cluster }}"
  vars_files:
  - "{{ cluster_dir }}/main.yml"
  - "{{ cluster_dir }}/pki-{{ ca_name }}-ca.yml"
  - "{{ cluster_dir }}/pki-{{ ca_name }}-clients.yml"
    
- hosts: tag_group_worker
  gather_facts: False
  roles:
  - kubelet
  vars:
    cluster_dir: "{{ playbook_dir }}/clusters/{{ cluster }}"
    workspace: "{{ cluster_dir }}/tmp"
  vars_files:
  - "{{ cluster_dir }}/main.yml"
  - "{{ cluster_dir }}/pki-{{ ca_name }}-ca.yml"
  - "{{ cluster_dir }}/pki-{{ ca_name }}-clients.yml"
