- set_fact:
    cfssl_ca_csr_dest: "{{ ca_dir }}/ca-csr.json"

- name: CA | generate CSR
  template: src=csr.json.j2 dest={{ cfssl_ca_csr_dest }} mode=0644
  vars:
    common_name: "{{ ca_name }}"
    hosts: []

- name: CA | generate private key
  shell: "cfssl gencert -initca {{ cfssl_ca_csr_dest }} | cfssljson -bare ca"
  args:
    chdir: "{{ workspace }}"

- name: CA | read cert
  command: "cat {{ workspace }}/ca.pem"
  register: ca_cert_shell
- name: CA | read private key
  command: "cat {{ workspace }}/ca-key.pem"
  register: ca_key_shell
- name: CA | set vars
  set_fact:
    ca_cert: "{{ ca_cert_shell.stdout }}"
    ca_key: "{{ ca_key_shell.stdout }}"

- name: CA | stash CA in vars file
  template: src=ca.yml.j2 dest={{ ca_vars_file }}

- name: CA | clean up workspace
  file: path={{ item }} state=absent
  with_fileglob:
  - "{{ workspace }}/*"
