- set_fact:
    ca_cert_file: "{{ workspace }}/ca.pem"
    ca_key_file: "{{ workspace }}/ca-key.pem"
    cfssl_ca_config: "{{ ca_dir }}/ca-config.json"

- name: create workspace
  file: path={{ workspace }} state=directory

- name: create CA dir
  file: path={{ ca_dir }} state=directory

- name: create output vars dir
  file: path={{ ca_vars_file | dirname }} state=directory

- name: create cfssl CA config
  template: src=ca-config.json.j2 dest={{ cfssl_ca_config }} mode=0644

- name: check for CA existence
  stat: path={{ ca_vars_file }}
  register: cmd

- name: create CA
  include: create-ca.yml
  when: not cmd.stat.exists

- name: read CA file
  include_vars: "{{ ca_vars_file }}"

- name: update CA file
  include: update-clients.yml
