- name: write CA cert file
  copy: content={{ pki_ca.cert }} dest={{ ca_cert_file }} mode=0644
- name: write CA key file
  copy: content={{ pki_ca.key }} dest={{ ca_key_file }} mode=0644

- name: check for clients existence
  stat: path={{ client_vars_file }}
  register: cmd

- name: read clients file
  include_vars: "{{ client_vars_file }}"
  when: cmd.stat.exists

- name: create clients
  include: create-client.yml 
  with_items: "{{ clients }}"
  when: client_{{ item.name }}_cert is not defined

- name: write client vars file
  template: src=clients.yml.j2 dest={{ client_vars_file }}

- name: clean up workspace
  file: path={{ item }} state=absent
  with_fileglob:
  - "{{ workspace }}/*"
