#!/bin/bash -e

operating_systems=( "linux" )
arch="amd64"
cmds=( "journalbeat" )
cmd_pkg="github.com/bcwaldon/klondike/src"

for os in "${operating_systems[@]}"; do
	bindir=bin/${os}_${arch}
	mkdir -p $bindir
	for cmd in "${cmds[@]}"; do
		artifact=$bindir/$cmd
		echo -n "Building $artifact..."
		GOOS=$os GOARCH=$arch go build -o $artifact $cmd_pkg/$cmd
		echo "done"
	done
done
