#!/bin/bash -e

operating_systems=( "darwin" "linux" )
arch="amd64"
cmds=( "farva-gateway" )
cmd_pkg="github.com/bcwaldon/klondike/src/farva/cmd"

for os in "${operating_systems[@]}"; do
	bindir=bin/${os}_${arch}
	mkdir -p $bindir
	for cmd in "${cmds[@]}"; do
		artifact=$bindir/$cmd
		echo -n "Building $artifact..."
		CGO_ENABLED=0 GOOS=$os GOARCH=$arch go build -a -ldflags '-s' -installsuffix cgo -o $artifact $cmd_pkg/$cmd
		echo "done"
	done
done
