- name: daemon-reload
  shell: systemctl daemon-reload
  sudo: true

- name: restart kubelet.service
  service: name=kubelet.service state=restarted
  sudo: true

- name: restart docker.service
  service: name=docker.service state=restarted
  sudo: true
