#
# Copyright 2016 Planet Labs
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
- name: upload pod manifests
  template: src={{ item }}.j2 dest=/etc/kubernetes/manifests/{{ item }} mode=0644
  sudo: true
  with_items:
  - gateway.yml

- name: create dd-agent config dir
  when: datadog_enabled
  sudo: true
  file: path=/etc/dd-agent/conf.d state=directory

- name: upload dd-agent nginx config
  when: datadog_enabled
  copy: src={{ item }} dest=/etc/dd-agent/conf.d/{{ item }} mode=0644
  sudo: true
  with_items:
  - nginx.yaml
