- name: render addon
  template: src={{ item }}.j2 dest={{ workspace }}/{{ item }}

- name: create addon
  command: kubectl --kubeconfig={{ cluster_dir }}/kubeconfig create -f {{ workspace }}/{{ item }}
