- name: generate CA CSR
  template: src=csr.json.j2 dest={{workspace}}/ca-csr.json mode=0644
  vars:
    common_name: "{{ ca_name }}"
    hosts: []

- name: generate CA private key
  shell: "cfssl gencert -initca ca-csr.json | cfssljson -bare ca"
  args:
    chdir: "{{ workspace }}"

- name: read cert file
  command: "cat {{ workspace }}/ca.pem"
  register: ca_cert_shell
- name: read private key file
  command: "cat {{ workspace }}/ca-key.pem"
  register: ca_key_shell
- name: set vars from files
  set_fact:
    ca_cert: "{{ ca_cert_shell.stdout }}"
    ca_key: "{{ ca_key_shell.stdout }}"

- name: create CA vars file
  template: src=ca.yml.j2 dest={{ ca_vars_file }}
