- set_fact:
    ca_cert_file: "{{ workspace }}/ca.pem"
    ca_key_file: "{{ workspace }}/ca-key.pem"

- name: create workspace
  file: path={{ workspace }} state=directory

- name: check for CA existence
  stat: path={{ ca_vars_file }}
  register: cmd

- name: create CA if necessary
  include: create-ca.yml
  when: not cmd.stat.exists
 
- name: destroy workspace
  file: path={{ item }} state=absent
  with_fileglob:
  - "{{ workspace }}/*"
