- set_fact:
    cert_name: "{{ item.name }}"
    cert_profile: "{{ item.profile }}"
    cfssl_cert_csr: "cert-{{ item.name }}-csr.json"

- name: CERT | generate CSR
  template: src=csr.json.j2 dest={{workspace}}/{{ cfssl_cert_csr }} mode=0644
  vars:
    common_name: "{{ cert_name }}"
    hosts: "{{ item.hosts }}"

- name: CERT | {{ cert_name }} | generate private key
  shell: "cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile={{ cert_profile }} {{ cfssl_cert_csr }} | cfssljson -bare {{ cert_name }}"
  args:
    chdir: "{{ workspace }}"

- name: read cert
  command: "cat {{ workspace }}/{{ cert_name }}.pem"
  register: cert_shell
- name: read key
  command: "cat {{ workspace }}/{{ cert_name }}-key.pem"
  register: key_shell

- set_fact:
    pki_clients: "{{ pki_clients | set_key(cert_name, dict(cert=cert_shell.stdout, key=key_shell.stdout)) }}"
