- set_fact:
    ca_cert_file: "{{ workspace }}/ca.pem"
    ca_key_file: "{{ workspace }}/ca-key.pem"
    cfssl_ca_config: "{{ workspace }}/ca-config.json"

- name: create directories
  file: path={{ item }} state=directory
  with_items:
  - "{{ workspace }}"
  - "{{ client_vars_file | dirname }}"

- name: read CA vars file
  include_vars: "{{ ca_vars_file }}"

- name: create CA config file
  template: src=ca-config.json.j2 dest={{ cfssl_ca_config }} mode=0644

- name: update clients file
  include: update-clients.yml

- name: clean up workspace
  file: path={{ item }} state=absent
  with_fileglob:
  - "{{ workspace }}/*"
