- name: write CA files
  copy: content={{ item.content }} dest={{ item.dest }} mode=0644
  with_items:
  - content: "{{ pki_ca_cert }}"
    dest: "{{ ca_cert_file }}"
  - content: "{{ pki_ca_key }}"
    dest: "{{ ca_key_file }}"

- name: check for clients existence
  stat: path={{ client_vars_file }}
  register: cmd

- name: read clients file
  include_vars: "{{ client_vars_file }}"
  when: cmd.stat.exists

- name: create missing clients
  include: create-client.yml 
  with_items: "{{ clients }}"
  when: pki_client_{{ item.name }}_cert is not defined

- name: write client vars file
  template: src=clients.yml.j2 dest={{ client_vars_file }}
